global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

scrape_configs:
  # Prometheus server itself
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - localhost:9090/prometheus #or server ip

  # cAdvisor
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080